name: Build Agent

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup go
        uses: https://github.com/actions/setup-go@v6
        with:
          go-version: ">=1.25.5"
      - name: Build
        run: ./build.sh agent
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: agent
          path: dist/agent
          retention-days: 7
  docker:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Fix Docker Permission
        uses: https://github.com/imlonghao/gitea-runner-docker-permission-fix@main
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: agent
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: git.esd.cc
          username: imlonghao
          password: ${{ secrets.IMLONGHAO_PACKAGES_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: git.esd.cc/imlonghao/mtr.sb-agent
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile.agent
          context: .
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: agent
      - name: Setup go
        uses: https://github.com/actions/setup-go@v6
        with:
          go-version: ">=1.25.5"
      - name: Release
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            agent
          api_key: ${{ secrets.IMLONGHAO_BOT_TOKEN }}
