// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/mtrsb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MtrSbWorker_Ping_FullMethodName       = "/MtrSbWorker/Ping"
	MtrSbWorker_Version_FullMethodName    = "/MtrSbWorker/Version"
	MtrSbWorker_Traceroute_FullMethodName = "/MtrSbWorker/Traceroute"
	MtrSbWorker_Mtr_FullMethodName        = "/MtrSbWorker/Mtr"
)

// MtrSbWorkerClient is the client API for MtrSbWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MtrSbWorkerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResponse], error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TracerouteResponse], error)
	Mtr(ctx context.Context, in *MtrRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MtrResponse], error)
}

type mtrSbWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewMtrSbWorkerClient(cc grpc.ClientConnInterface) MtrSbWorkerClient {
	return &mtrSbWorkerClient{cc}
}

func (c *mtrSbWorkerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MtrSbWorker_ServiceDesc.Streams[0], MtrSbWorker_Ping_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PingRequest, PingResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtrSbWorker_PingClient = grpc.ServerStreamingClient[PingResponse]

func (c *mtrSbWorkerClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, MtrSbWorker_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mtrSbWorkerClient) Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TracerouteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MtrSbWorker_ServiceDesc.Streams[1], MtrSbWorker_Traceroute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TracerouteRequest, TracerouteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtrSbWorker_TracerouteClient = grpc.ServerStreamingClient[TracerouteResponse]

func (c *mtrSbWorkerClient) Mtr(ctx context.Context, in *MtrRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MtrResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MtrSbWorker_ServiceDesc.Streams[2], MtrSbWorker_Mtr_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MtrRequest, MtrResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtrSbWorker_MtrClient = grpc.ServerStreamingClient[MtrResponse]

// MtrSbWorkerServer is the server API for MtrSbWorker service.
// All implementations must embed UnimplementedMtrSbWorkerServer
// for forward compatibility.
type MtrSbWorkerServer interface {
	Ping(*PingRequest, grpc.ServerStreamingServer[PingResponse]) error
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	Traceroute(*TracerouteRequest, grpc.ServerStreamingServer[TracerouteResponse]) error
	Mtr(*MtrRequest, grpc.ServerStreamingServer[MtrResponse]) error
	mustEmbedUnimplementedMtrSbWorkerServer()
}

// UnimplementedMtrSbWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMtrSbWorkerServer struct{}

func (UnimplementedMtrSbWorkerServer) Ping(*PingRequest, grpc.ServerStreamingServer[PingResponse]) error {
	return status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMtrSbWorkerServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedMtrSbWorkerServer) Traceroute(*TracerouteRequest, grpc.ServerStreamingServer[TracerouteResponse]) error {
	return status.Error(codes.Unimplemented, "method Traceroute not implemented")
}
func (UnimplementedMtrSbWorkerServer) Mtr(*MtrRequest, grpc.ServerStreamingServer[MtrResponse]) error {
	return status.Error(codes.Unimplemented, "method Mtr not implemented")
}
func (UnimplementedMtrSbWorkerServer) mustEmbedUnimplementedMtrSbWorkerServer() {}
func (UnimplementedMtrSbWorkerServer) testEmbeddedByValue()                     {}

// UnsafeMtrSbWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MtrSbWorkerServer will
// result in compilation errors.
type UnsafeMtrSbWorkerServer interface {
	mustEmbedUnimplementedMtrSbWorkerServer()
}

func RegisterMtrSbWorkerServer(s grpc.ServiceRegistrar, srv MtrSbWorkerServer) {
	// If the following call panics, it indicates UnimplementedMtrSbWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MtrSbWorker_ServiceDesc, srv)
}

func _MtrSbWorker_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MtrSbWorkerServer).Ping(m, &grpc.GenericServerStream[PingRequest, PingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtrSbWorker_PingServer = grpc.ServerStreamingServer[PingResponse]

func _MtrSbWorker_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MtrSbWorkerServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MtrSbWorker_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MtrSbWorkerServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MtrSbWorker_Traceroute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TracerouteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MtrSbWorkerServer).Traceroute(m, &grpc.GenericServerStream[TracerouteRequest, TracerouteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtrSbWorker_TracerouteServer = grpc.ServerStreamingServer[TracerouteResponse]

func _MtrSbWorker_Mtr_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MtrRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MtrSbWorkerServer).Mtr(m, &grpc.GenericServerStream[MtrRequest, MtrResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtrSbWorker_MtrServer = grpc.ServerStreamingServer[MtrResponse]

// MtrSbWorker_ServiceDesc is the grpc.ServiceDesc for MtrSbWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MtrSbWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MtrSbWorker",
	HandlerType: (*MtrSbWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _MtrSbWorker_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _MtrSbWorker_Ping_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Traceroute",
			Handler:       _MtrSbWorker_Traceroute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Mtr",
			Handler:       _MtrSbWorker_Mtr_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mtrsb.proto",
}
