// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/mtrsb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_ANY  Protocol = 0
	Protocol_IPV4 Protocol = 1
	Protocol_IPV6 Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "ANY",
		1: "IPV4",
		2: "IPV6",
	}
	Protocol_value = map[string]int32{
		"ANY":  0,
		"IPV4": 1,
		"IPV6": 2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mtrsb_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_mtrsb_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{0}
}

type TaskType int32

const (
	TaskType_TASK_VERSION    TaskType = 0
	TaskType_TASK_PING       TaskType = 1
	TaskType_TASK_MTR        TaskType = 2
	TaskType_TASK_TRACEROUTE TaskType = 3
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_VERSION",
		1: "TASK_PING",
		2: "TASK_MTR",
		3: "TASK_TRACEROUTE",
	}
	TaskType_value = map[string]int32{
		"TASK_VERSION":    0,
		"TASK_PING":       1,
		"TASK_MTR":        2,
		"TASK_TRACEROUTE": 3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mtrsb_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_mtrsb_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{1}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_mtrsb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PingRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_ANY
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*PingResponse_Reply
	//	*PingResponse_Timeout
	//	*PingResponse_Summary
	//	*PingResponse_Error
	//	*PingResponse_Lookup
	Response      isPingResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_mtrsb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetResponse() isPingResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PingResponse) GetReply() *PingReply {
	if x != nil {
		if x, ok := x.Response.(*PingResponse_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *PingResponse) GetTimeout() *PingTimeout {
	if x != nil {
		if x, ok := x.Response.(*PingResponse_Timeout); ok {
			return x.Timeout
		}
	}
	return nil
}

func (x *PingResponse) GetSummary() *PingSummary {
	if x != nil {
		if x, ok := x.Response.(*PingResponse_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

func (x *PingResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*PingResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *PingResponse) GetLookup() *HostLookupResult {
	if x != nil {
		if x, ok := x.Response.(*PingResponse_Lookup); ok {
			return x.Lookup
		}
	}
	return nil
}

type isPingResponse_Response interface {
	isPingResponse_Response()
}

type PingResponse_Reply struct {
	Reply *PingReply `protobuf:"bytes,1,opt,name=reply,proto3,oneof"`
}

type PingResponse_Timeout struct {
	Timeout *PingTimeout `protobuf:"bytes,2,opt,name=timeout,proto3,oneof"`
}

type PingResponse_Summary struct {
	Summary *PingSummary `protobuf:"bytes,3,opt,name=summary,proto3,oneof"`
}

type PingResponse_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type PingResponse_Lookup struct {
	Lookup *HostLookupResult `protobuf:"bytes,5,opt,name=lookup,proto3,oneof"`
}

func (*PingResponse_Reply) isPingResponse_Response() {}

func (*PingResponse_Timeout) isPingResponse_Response() {}

func (*PingResponse_Summary) isPingResponse_Response() {}

func (*PingResponse_Error) isPingResponse_Response() {}

func (*PingResponse_Lookup) isPingResponse_Response() {}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rtt           float32                `protobuf:"fixed32,1,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Ttl           int32                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Seq           int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Bytes         int32                  `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_proto_mtrsb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{2}
}

func (x *PingReply) GetRtt() float32 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

func (x *PingReply) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *PingReply) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PingReply) GetBytes() int32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type PingTimeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingTimeout) Reset() {
	*x = PingTimeout{}
	mi := &file_proto_mtrsb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingTimeout) ProtoMessage() {}

func (x *PingTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingTimeout.ProtoReflect.Descriptor instead.
func (*PingTimeout) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{3}
}

func (x *PingTimeout) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PingSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          int32                  `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Received      int32                  `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingSummary) Reset() {
	*x = PingSummary{}
	mi := &file_proto_mtrsb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingSummary) ProtoMessage() {}

func (x *PingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingSummary.ProtoReflect.Descriptor instead.
func (*PingSummary) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{4}
}

func (x *PingSummary) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *PingSummary) GetReceived() int32 {
	if x != nil {
		return x.Received
	}
	return 0
}

type HostLookupResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostLookupResult) Reset() {
	*x = HostLookupResult{}
	mi := &file_proto_mtrsb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostLookupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostLookupResult) ProtoMessage() {}

func (x *HostLookupResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostLookupResult.ProtoReflect.Descriptor instead.
func (*HostLookupResult) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{5}
}

func (x *HostLookupResult) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_mtrsb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_proto_mtrsb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{7}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_mtrsb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{8}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TracerouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteRequest) Reset() {
	*x = TracerouteRequest{}
	mi := &file_proto_mtrsb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteRequest) ProtoMessage() {}

func (x *TracerouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteRequest.ProtoReflect.Descriptor instead.
func (*TracerouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{9}
}

func (x *TracerouteRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TracerouteRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_ANY
}

type TracerouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TracerouteResponse_Reply
	//	*TracerouteResponse_Timeout
	//	*TracerouteResponse_Error
	//	*TracerouteResponse_Completed
	//	*TracerouteResponse_Lookup
	Response      isTracerouteResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteResponse) Reset() {
	*x = TracerouteResponse{}
	mi := &file_proto_mtrsb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteResponse) ProtoMessage() {}

func (x *TracerouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteResponse.ProtoReflect.Descriptor instead.
func (*TracerouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{10}
}

func (x *TracerouteResponse) GetResponse() isTracerouteResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TracerouteResponse) GetReply() *TracerouteReply {
	if x != nil {
		if x, ok := x.Response.(*TracerouteResponse_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *TracerouteResponse) GetTimeout() *PingTimeout {
	if x != nil {
		if x, ok := x.Response.(*TracerouteResponse_Timeout); ok {
			return x.Timeout
		}
	}
	return nil
}

func (x *TracerouteResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*TracerouteResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *TracerouteResponse) GetCompleted() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Response.(*TracerouteResponse_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *TracerouteResponse) GetLookup() *HostLookupResult {
	if x != nil {
		if x, ok := x.Response.(*TracerouteResponse_Lookup); ok {
			return x.Lookup
		}
	}
	return nil
}

type isTracerouteResponse_Response interface {
	isTracerouteResponse_Response()
}

type TracerouteResponse_Reply struct {
	Reply *TracerouteReply `protobuf:"bytes,1,opt,name=reply,proto3,oneof"`
}

type TracerouteResponse_Timeout struct {
	Timeout *PingTimeout `protobuf:"bytes,2,opt,name=timeout,proto3,oneof"`
}

type TracerouteResponse_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type TracerouteResponse_Completed struct {
	Completed *emptypb.Empty `protobuf:"bytes,4,opt,name=completed,proto3,oneof"`
}

type TracerouteResponse_Lookup struct {
	Lookup *HostLookupResult `protobuf:"bytes,5,opt,name=lookup,proto3,oneof"`
}

func (*TracerouteResponse_Reply) isTracerouteResponse_Response() {}

func (*TracerouteResponse_Timeout) isTracerouteResponse_Response() {}

func (*TracerouteResponse_Error) isTracerouteResponse_Response() {}

func (*TracerouteResponse_Completed) isTracerouteResponse_Response() {}

func (*TracerouteResponse_Lookup) isTracerouteResponse_Response() {}

type TracerouteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Rtt           float32                `protobuf:"fixed32,3,opt,name=rtt,proto3" json:"rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteReply) Reset() {
	*x = TracerouteReply{}
	mi := &file_proto_mtrsb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteReply) ProtoMessage() {}

func (x *TracerouteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteReply.ProtoReflect.Descriptor instead.
func (*TracerouteReply) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{11}
}

func (x *TracerouteReply) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TracerouteReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TracerouteReply) GetRtt() float32 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

type MtrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtrRequest) Reset() {
	*x = MtrRequest{}
	mi := &file_proto_mtrsb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtrRequest) ProtoMessage() {}

func (x *MtrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtrRequest.ProtoReflect.Descriptor instead.
func (*MtrRequest) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{12}
}

func (x *MtrRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MtrRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_ANY
}

type MtrResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pos   uint32                 `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*MtrResponse_Lookup
	//	*MtrResponse_Host
	//	*MtrResponse_Transmit
	//	*MtrResponse_Ping
	//	*MtrResponse_Dns
	//	*MtrResponse_Error
	Response      isMtrResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtrResponse) Reset() {
	*x = MtrResponse{}
	mi := &file_proto_mtrsb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtrResponse) ProtoMessage() {}

func (x *MtrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtrResponse.ProtoReflect.Descriptor instead.
func (*MtrResponse) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{13}
}

func (x *MtrResponse) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *MtrResponse) GetResponse() isMtrResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MtrResponse) GetLookup() *HostLookupResult {
	if x != nil {
		if x, ok := x.Response.(*MtrResponse_Lookup); ok {
			return x.Lookup
		}
	}
	return nil
}

func (x *MtrResponse) GetHost() *MtrHostLine {
	if x != nil {
		if x, ok := x.Response.(*MtrResponse_Host); ok {
			return x.Host
		}
	}
	return nil
}

func (x *MtrResponse) GetTransmit() *MtrTransmitLine {
	if x != nil {
		if x, ok := x.Response.(*MtrResponse_Transmit); ok {
			return x.Transmit
		}
	}
	return nil
}

func (x *MtrResponse) GetPing() *MtrPingLine {
	if x != nil {
		if x, ok := x.Response.(*MtrResponse_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *MtrResponse) GetDns() *MtrDnsLine {
	if x != nil {
		if x, ok := x.Response.(*MtrResponse_Dns); ok {
			return x.Dns
		}
	}
	return nil
}

func (x *MtrResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*MtrResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isMtrResponse_Response interface {
	isMtrResponse_Response()
}

type MtrResponse_Lookup struct {
	Lookup *HostLookupResult `protobuf:"bytes,2,opt,name=lookup,proto3,oneof"`
}

type MtrResponse_Host struct {
	Host *MtrHostLine `protobuf:"bytes,3,opt,name=host,proto3,oneof"`
}

type MtrResponse_Transmit struct {
	Transmit *MtrTransmitLine `protobuf:"bytes,4,opt,name=transmit,proto3,oneof"`
}

type MtrResponse_Ping struct {
	Ping *MtrPingLine `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type MtrResponse_Dns struct {
	Dns *MtrDnsLine `protobuf:"bytes,6,opt,name=dns,proto3,oneof"`
}

type MtrResponse_Error struct {
	Error *Error `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*MtrResponse_Lookup) isMtrResponse_Response() {}

func (*MtrResponse_Host) isMtrResponse_Response() {}

func (*MtrResponse_Transmit) isMtrResponse_Response() {}

func (*MtrResponse_Ping) isMtrResponse_Response() {}

func (*MtrResponse_Dns) isMtrResponse_Response() {}

func (*MtrResponse_Error) isMtrResponse_Response() {}

type MtrHostLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtrHostLine) Reset() {
	*x = MtrHostLine{}
	mi := &file_proto_mtrsb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtrHostLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtrHostLine) ProtoMessage() {}

func (x *MtrHostLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtrHostLine.ProtoReflect.Descriptor instead.
func (*MtrHostLine) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{14}
}

func (x *MtrHostLine) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type MtrTransmitLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqnum        uint32                 `protobuf:"varint,1,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtrTransmitLine) Reset() {
	*x = MtrTransmitLine{}
	mi := &file_proto_mtrsb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtrTransmitLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtrTransmitLine) ProtoMessage() {}

func (x *MtrTransmitLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtrTransmitLine.ProtoReflect.Descriptor instead.
func (*MtrTransmitLine) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{15}
}

func (x *MtrTransmitLine) GetSeqnum() uint32 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

type MtrPingLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rtt           float32                `protobuf:"fixed32,1,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Seqnum        uint32                 `protobuf:"varint,2,opt,name=seqnum,proto3" json:"seqnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtrPingLine) Reset() {
	*x = MtrPingLine{}
	mi := &file_proto_mtrsb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtrPingLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtrPingLine) ProtoMessage() {}

func (x *MtrPingLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtrPingLine.ProtoReflect.Descriptor instead.
func (*MtrPingLine) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{16}
}

func (x *MtrPingLine) GetRtt() float32 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

func (x *MtrPingLine) GetSeqnum() uint32 {
	if x != nil {
		return x.Seqnum
	}
	return 0
}

type MtrDnsLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtrDnsLine) Reset() {
	*x = MtrDnsLine{}
	mi := &file_proto_mtrsb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtrDnsLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtrDnsLine) ProtoMessage() {}

func (x *MtrDnsLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtrDnsLine.ProtoReflect.Descriptor instead.
func (*MtrDnsLine) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{17}
}

func (x *MtrDnsLine) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type AgentRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegisterRequest) Reset() {
	*x = AgentRegisterRequest{}
	mi := &file_proto_mtrsb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterRequest) ProtoMessage() {}

func (x *AgentRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterRequest.ProtoReflect.Descriptor instead.
func (*AgentRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{18}
}

func (x *AgentRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentRegisterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type AgentRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Latitude      float32                `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegisterResponse) Reset() {
	*x = AgentRegisterResponse{}
	mi := &file_proto_mtrsb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterResponse) ProtoMessage() {}

func (x *AgentRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterResponse.ProtoReflect.Descriptor instead.
func (*AgentRegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{19}
}

func (x *AgentRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentRegisterResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AgentRegisterResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AgentRegisterResponse) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AgentRegisterResponse) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type TaskRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=TaskType" json:"task_type,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*TaskRequest_Ping
	//	*TaskRequest_Mtr
	//	*TaskRequest_Traceroute
	//	*TaskRequest_Version
	Request       isTaskRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_mtrsb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{20}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_VERSION
}

func (x *TaskRequest) GetRequest() isTaskRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TaskRequest) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Request.(*TaskRequest_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *TaskRequest) GetMtr() *MtrRequest {
	if x != nil {
		if x, ok := x.Request.(*TaskRequest_Mtr); ok {
			return x.Mtr
		}
	}
	return nil
}

func (x *TaskRequest) GetTraceroute() *TracerouteRequest {
	if x != nil {
		if x, ok := x.Request.(*TaskRequest_Traceroute); ok {
			return x.Traceroute
		}
	}
	return nil
}

func (x *TaskRequest) GetVersion() *VersionRequest {
	if x != nil {
		if x, ok := x.Request.(*TaskRequest_Version); ok {
			return x.Version
		}
	}
	return nil
}

type isTaskRequest_Request interface {
	isTaskRequest_Request()
}

type TaskRequest_Ping struct {
	Ping *PingRequest `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type TaskRequest_Mtr struct {
	Mtr *MtrRequest `protobuf:"bytes,4,opt,name=mtr,proto3,oneof"`
}

type TaskRequest_Traceroute struct {
	Traceroute *TracerouteRequest `protobuf:"bytes,5,opt,name=traceroute,proto3,oneof"`
}

type TaskRequest_Version struct {
	Version *VersionRequest `protobuf:"bytes,6,opt,name=version,proto3,oneof"`
}

func (*TaskRequest_Ping) isTaskRequest_Request() {}

func (*TaskRequest_Mtr) isTaskRequest_Request() {}

func (*TaskRequest_Traceroute) isTaskRequest_Request() {}

func (*TaskRequest_Version) isTaskRequest_Request() {}

type TaskResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=TaskType" json:"task_type,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*TaskResponse_Ping
	//	*TaskResponse_Mtr
	//	*TaskResponse_Traceroute
	//	*TaskResponse_Version
	Response      isTaskResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_mtrsb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mtrsb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_mtrsb_proto_rawDescGZIP(), []int{21}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_VERSION
}

func (x *TaskResponse) GetResponse() isTaskResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TaskResponse) GetPing() *PingResponse {
	if x != nil {
		if x, ok := x.Response.(*TaskResponse_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *TaskResponse) GetMtr() *MtrResponse {
	if x != nil {
		if x, ok := x.Response.(*TaskResponse_Mtr); ok {
			return x.Mtr
		}
	}
	return nil
}

func (x *TaskResponse) GetTraceroute() *TracerouteResponse {
	if x != nil {
		if x, ok := x.Response.(*TaskResponse_Traceroute); ok {
			return x.Traceroute
		}
	}
	return nil
}

func (x *TaskResponse) GetVersion() *VersionResponse {
	if x != nil {
		if x, ok := x.Response.(*TaskResponse_Version); ok {
			return x.Version
		}
	}
	return nil
}

type isTaskResponse_Response interface {
	isTaskResponse_Response()
}

type TaskResponse_Ping struct {
	Ping *PingResponse `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type TaskResponse_Mtr struct {
	Mtr *MtrResponse `protobuf:"bytes,4,opt,name=mtr,proto3,oneof"`
}

type TaskResponse_Traceroute struct {
	Traceroute *TracerouteResponse `protobuf:"bytes,5,opt,name=traceroute,proto3,oneof"`
}

type TaskResponse_Version struct {
	Version *VersionResponse `protobuf:"bytes,6,opt,name=version,proto3,oneof"`
}

func (*TaskResponse_Ping) isTaskResponse_Response() {}

func (*TaskResponse_Mtr) isTaskResponse_Response() {}

func (*TaskResponse_Traceroute) isTaskResponse_Response() {}

func (*TaskResponse_Version) isTaskResponse_Response() {}

var File_proto_mtrsb_proto protoreflect.FileDescriptor

const file_proto_mtrsb_proto_rawDesc = "" +
	"\n" +
	"\x11proto/mtrsb.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12%\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\t.ProtocolR\bprotocol\"\xdf\x01\n" +
	"\fPingResponse\x12\"\n" +
	"\x05reply\x18\x01 \x01(\v2\n" +
	".PingReplyH\x00R\x05reply\x12(\n" +
	"\atimeout\x18\x02 \x01(\v2\f.PingTimeoutH\x00R\atimeout\x12(\n" +
	"\asummary\x18\x03 \x01(\v2\f.PingSummaryH\x00R\asummary\x12\x1e\n" +
	"\x05error\x18\x04 \x01(\v2\x06.ErrorH\x00R\x05error\x12+\n" +
	"\x06lookup\x18\x05 \x01(\v2\x11.HostLookupResultH\x00R\x06lookupB\n" +
	"\n" +
	"\bresponse\"W\n" +
	"\tPingReply\x12\x10\n" +
	"\x03rtt\x18\x01 \x01(\x02R\x03rtt\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x05R\x03ttl\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seq\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\x05R\x05bytes\"\x1f\n" +
	"\vPingTimeout\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\"=\n" +
	"\vPingSummary\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\x05R\x04sent\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\x05R\breceived\"\"\n" +
	"\x10HostLookupResult\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"7\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x10\n" +
	"\x0eVersionRequest\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"N\n" +
	"\x11TracerouteRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12%\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\t.ProtocolR\bprotocol\"\xf9\x01\n" +
	"\x12TracerouteResponse\x12(\n" +
	"\x05reply\x18\x01 \x01(\v2\x10.TracerouteReplyH\x00R\x05reply\x12(\n" +
	"\atimeout\x18\x02 \x01(\v2\f.PingTimeoutH\x00R\atimeout\x12\x1e\n" +
	"\x05error\x18\x03 \x01(\v2\x06.ErrorH\x00R\x05error\x126\n" +
	"\tcompleted\x18\x04 \x01(\v2\x16.google.protobuf.EmptyH\x00R\tcompleted\x12+\n" +
	"\x06lookup\x18\x05 \x01(\v2\x11.HostLookupResultH\x00R\x06lookupB\n" +
	"\n" +
	"\bresponse\"E\n" +
	"\x0fTracerouteReply\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03rtt\x18\x03 \x01(\x02R\x03rtt\"G\n" +
	"\n" +
	"MtrRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12%\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\t.ProtocolR\bprotocol\"\x91\x02\n" +
	"\vMtrResponse\x12\x10\n" +
	"\x03pos\x18\x01 \x01(\rR\x03pos\x12+\n" +
	"\x06lookup\x18\x02 \x01(\v2\x11.HostLookupResultH\x00R\x06lookup\x12\"\n" +
	"\x04host\x18\x03 \x01(\v2\f.MtrHostLineH\x00R\x04host\x12.\n" +
	"\btransmit\x18\x04 \x01(\v2\x10.MtrTransmitLineH\x00R\btransmit\x12\"\n" +
	"\x04ping\x18\x05 \x01(\v2\f.MtrPingLineH\x00R\x04ping\x12\x1f\n" +
	"\x03dns\x18\x06 \x01(\v2\v.MtrDnsLineH\x00R\x03dns\x12\x1e\n" +
	"\x05error\x18\a \x01(\v2\x06.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x1d\n" +
	"\vMtrHostLine\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\")\n" +
	"\x0fMtrTransmitLine\x12\x16\n" +
	"\x06seqnum\x18\x01 \x01(\rR\x06seqnum\"7\n" +
	"\vMtrPingLine\x12\x10\n" +
	"\x03rtt\x18\x01 \x01(\x02R\x03rtt\x12\x16\n" +
	"\x06seqnum\x18\x02 \x01(\rR\x06seqnum\"(\n" +
	"\n" +
	"MtrDnsLine\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"F\n" +
	"\x14AgentRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\xbb\x01\n" +
	"\x15AgentRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x02R\tlongitude\"\x81\x02\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\t.TaskTypeR\btaskType\x12\"\n" +
	"\x04ping\x18\x03 \x01(\v2\f.PingRequestH\x00R\x04ping\x12\x1f\n" +
	"\x03mtr\x18\x04 \x01(\v2\v.MtrRequestH\x00R\x03mtr\x124\n" +
	"\n" +
	"traceroute\x18\x05 \x01(\v2\x12.TracerouteRequestH\x00R\n" +
	"traceroute\x12+\n" +
	"\aversion\x18\x06 \x01(\v2\x0f.VersionRequestH\x00R\aversionB\t\n" +
	"\arequest\"\x87\x02\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\t.TaskTypeR\btaskType\x12#\n" +
	"\x04ping\x18\x03 \x01(\v2\r.PingResponseH\x00R\x04ping\x12 \n" +
	"\x03mtr\x18\x04 \x01(\v2\f.MtrResponseH\x00R\x03mtr\x125\n" +
	"\n" +
	"traceroute\x18\x05 \x01(\v2\x13.TracerouteResponseH\x00R\n" +
	"traceroute\x12,\n" +
	"\aversion\x18\x06 \x01(\v2\x10.VersionResponseH\x00R\aversionB\n" +
	"\n" +
	"\bresponse*'\n" +
	"\bProtocol\x12\a\n" +
	"\x03ANY\x10\x00\x12\b\n" +
	"\x04IPV4\x10\x01\x12\b\n" +
	"\x04IPV6\x10\x02*N\n" +
	"\bTaskType\x12\x10\n" +
	"\fTASK_VERSION\x10\x00\x12\r\n" +
	"\tTASK_PING\x10\x01\x12\f\n" +
	"\bTASK_MTR\x10\x02\x12\x13\n" +
	"\x0fTASK_TRACEROUTE\x10\x032\xbf\x01\n" +
	"\vMtrSbWorker\x12%\n" +
	"\x04Ping\x12\f.PingRequest\x1a\r.PingResponse0\x01\x12,\n" +
	"\aVersion\x12\x0f.VersionRequest\x1a\x10.VersionResponse\x127\n" +
	"\n" +
	"Traceroute\x12\x12.TracerouteRequest\x1a\x13.TracerouteResponse0\x01\x12\"\n" +
	"\x03Mtr\x12\v.MtrRequest\x1a\f.MtrResponse0\x01B\bZ\x06proto/b\x06proto3"

var (
	file_proto_mtrsb_proto_rawDescOnce sync.Once
	file_proto_mtrsb_proto_rawDescData []byte
)

func file_proto_mtrsb_proto_rawDescGZIP() []byte {
	file_proto_mtrsb_proto_rawDescOnce.Do(func() {
		file_proto_mtrsb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mtrsb_proto_rawDesc), len(file_proto_mtrsb_proto_rawDesc)))
	})
	return file_proto_mtrsb_proto_rawDescData
}

var file_proto_mtrsb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_mtrsb_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_mtrsb_proto_goTypes = []any{
	(Protocol)(0),                 // 0: Protocol
	(TaskType)(0),                 // 1: TaskType
	(*PingRequest)(nil),           // 2: PingRequest
	(*PingResponse)(nil),          // 3: PingResponse
	(*PingReply)(nil),             // 4: PingReply
	(*PingTimeout)(nil),           // 5: PingTimeout
	(*PingSummary)(nil),           // 6: PingSummary
	(*HostLookupResult)(nil),      // 7: HostLookupResult
	(*Error)(nil),                 // 8: Error
	(*VersionRequest)(nil),        // 9: VersionRequest
	(*VersionResponse)(nil),       // 10: VersionResponse
	(*TracerouteRequest)(nil),     // 11: TracerouteRequest
	(*TracerouteResponse)(nil),    // 12: TracerouteResponse
	(*TracerouteReply)(nil),       // 13: TracerouteReply
	(*MtrRequest)(nil),            // 14: MtrRequest
	(*MtrResponse)(nil),           // 15: MtrResponse
	(*MtrHostLine)(nil),           // 16: MtrHostLine
	(*MtrTransmitLine)(nil),       // 17: MtrTransmitLine
	(*MtrPingLine)(nil),           // 18: MtrPingLine
	(*MtrDnsLine)(nil),            // 19: MtrDnsLine
	(*AgentRegisterRequest)(nil),  // 20: AgentRegisterRequest
	(*AgentRegisterResponse)(nil), // 21: AgentRegisterResponse
	(*TaskRequest)(nil),           // 22: TaskRequest
	(*TaskResponse)(nil),          // 23: TaskResponse
	(*emptypb.Empty)(nil),         // 24: google.protobuf.Empty
}
var file_proto_mtrsb_proto_depIdxs = []int32{
	0,  // 0: PingRequest.protocol:type_name -> Protocol
	4,  // 1: PingResponse.reply:type_name -> PingReply
	5,  // 2: PingResponse.timeout:type_name -> PingTimeout
	6,  // 3: PingResponse.summary:type_name -> PingSummary
	8,  // 4: PingResponse.error:type_name -> Error
	7,  // 5: PingResponse.lookup:type_name -> HostLookupResult
	0,  // 6: TracerouteRequest.protocol:type_name -> Protocol
	13, // 7: TracerouteResponse.reply:type_name -> TracerouteReply
	5,  // 8: TracerouteResponse.timeout:type_name -> PingTimeout
	8,  // 9: TracerouteResponse.error:type_name -> Error
	24, // 10: TracerouteResponse.completed:type_name -> google.protobuf.Empty
	7,  // 11: TracerouteResponse.lookup:type_name -> HostLookupResult
	0,  // 12: MtrRequest.protocol:type_name -> Protocol
	7,  // 13: MtrResponse.lookup:type_name -> HostLookupResult
	16, // 14: MtrResponse.host:type_name -> MtrHostLine
	17, // 15: MtrResponse.transmit:type_name -> MtrTransmitLine
	18, // 16: MtrResponse.ping:type_name -> MtrPingLine
	19, // 17: MtrResponse.dns:type_name -> MtrDnsLine
	8,  // 18: MtrResponse.error:type_name -> Error
	1,  // 19: TaskRequest.task_type:type_name -> TaskType
	2,  // 20: TaskRequest.ping:type_name -> PingRequest
	14, // 21: TaskRequest.mtr:type_name -> MtrRequest
	11, // 22: TaskRequest.traceroute:type_name -> TracerouteRequest
	9,  // 23: TaskRequest.version:type_name -> VersionRequest
	1,  // 24: TaskResponse.task_type:type_name -> TaskType
	3,  // 25: TaskResponse.ping:type_name -> PingResponse
	15, // 26: TaskResponse.mtr:type_name -> MtrResponse
	12, // 27: TaskResponse.traceroute:type_name -> TracerouteResponse
	10, // 28: TaskResponse.version:type_name -> VersionResponse
	2,  // 29: MtrSbWorker.Ping:input_type -> PingRequest
	9,  // 30: MtrSbWorker.Version:input_type -> VersionRequest
	11, // 31: MtrSbWorker.Traceroute:input_type -> TracerouteRequest
	14, // 32: MtrSbWorker.Mtr:input_type -> MtrRequest
	3,  // 33: MtrSbWorker.Ping:output_type -> PingResponse
	10, // 34: MtrSbWorker.Version:output_type -> VersionResponse
	12, // 35: MtrSbWorker.Traceroute:output_type -> TracerouteResponse
	15, // 36: MtrSbWorker.Mtr:output_type -> MtrResponse
	33, // [33:37] is the sub-list for method output_type
	29, // [29:33] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_mtrsb_proto_init() }
func file_proto_mtrsb_proto_init() {
	if File_proto_mtrsb_proto != nil {
		return
	}
	file_proto_mtrsb_proto_msgTypes[1].OneofWrappers = []any{
		(*PingResponse_Reply)(nil),
		(*PingResponse_Timeout)(nil),
		(*PingResponse_Summary)(nil),
		(*PingResponse_Error)(nil),
		(*PingResponse_Lookup)(nil),
	}
	file_proto_mtrsb_proto_msgTypes[10].OneofWrappers = []any{
		(*TracerouteResponse_Reply)(nil),
		(*TracerouteResponse_Timeout)(nil),
		(*TracerouteResponse_Error)(nil),
		(*TracerouteResponse_Completed)(nil),
		(*TracerouteResponse_Lookup)(nil),
	}
	file_proto_mtrsb_proto_msgTypes[13].OneofWrappers = []any{
		(*MtrResponse_Lookup)(nil),
		(*MtrResponse_Host)(nil),
		(*MtrResponse_Transmit)(nil),
		(*MtrResponse_Ping)(nil),
		(*MtrResponse_Dns)(nil),
		(*MtrResponse_Error)(nil),
	}
	file_proto_mtrsb_proto_msgTypes[20].OneofWrappers = []any{
		(*TaskRequest_Ping)(nil),
		(*TaskRequest_Mtr)(nil),
		(*TaskRequest_Traceroute)(nil),
		(*TaskRequest_Version)(nil),
	}
	file_proto_mtrsb_proto_msgTypes[21].OneofWrappers = []any{
		(*TaskResponse_Ping)(nil),
		(*TaskResponse_Mtr)(nil),
		(*TaskResponse_Traceroute)(nil),
		(*TaskResponse_Version)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mtrsb_proto_rawDesc), len(file_proto_mtrsb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mtrsb_proto_goTypes,
		DependencyIndexes: file_proto_mtrsb_proto_depIdxs,
		EnumInfos:         file_proto_mtrsb_proto_enumTypes,
		MessageInfos:      file_proto_mtrsb_proto_msgTypes,
	}.Build()
	File_proto_mtrsb_proto = out.File
	file_proto_mtrsb_proto_goTypes = nil
	file_proto_mtrsb_proto_depIdxs = nil
}
