// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: proto/mtrsb.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { Empty } from "../google/protobuf/empty";

export const protobufPackage = "";

export enum Protocol {
  ANY = 0,
  IPV4 = 1,
  IPV6 = 2,
  UNRECOGNIZED = -1,
}

export function protocolFromJSON(object: any): Protocol {
  switch (object) {
    case 0:
    case "ANY":
      return Protocol.ANY;
    case 1:
    case "IPV4":
      return Protocol.IPV4;
    case 2:
    case "IPV6":
      return Protocol.IPV6;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Protocol.UNRECOGNIZED;
  }
}

export function protocolToJSON(object: Protocol): string {
  switch (object) {
    case Protocol.ANY:
      return "ANY";
    case Protocol.IPV4:
      return "IPV4";
    case Protocol.IPV6:
      return "IPV6";
    case Protocol.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TaskType {
  TASK_VERSION = 0,
  TASK_PING = 1,
  TASK_MTR = 2,
  TASK_TRACEROUTE = 3,
  UNRECOGNIZED = -1,
}

export function taskTypeFromJSON(object: any): TaskType {
  switch (object) {
    case 0:
    case "TASK_VERSION":
      return TaskType.TASK_VERSION;
    case 1:
    case "TASK_PING":
      return TaskType.TASK_PING;
    case 2:
    case "TASK_MTR":
      return TaskType.TASK_MTR;
    case 3:
    case "TASK_TRACEROUTE":
      return TaskType.TASK_TRACEROUTE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TaskType.UNRECOGNIZED;
  }
}

export function taskTypeToJSON(object: TaskType): string {
  switch (object) {
    case TaskType.TASK_VERSION:
      return "TASK_VERSION";
    case TaskType.TASK_PING:
      return "TASK_PING";
    case TaskType.TASK_MTR:
      return "TASK_MTR";
    case TaskType.TASK_TRACEROUTE:
      return "TASK_TRACEROUTE";
    case TaskType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface PingRequest {
  host: string;
  protocol: Protocol;
}

export interface PingResponse {
  reply?: PingReply | undefined;
  timeout?: PingTimeout | undefined;
  summary?: PingSummary | undefined;
  error?: Error | undefined;
  lookup?: HostLookupResult | undefined;
}

export interface PingReply {
  rtt: number;
  ttl: number;
  seq: number;
  bytes: number;
}

export interface PingTimeout {
  seq: number;
}

export interface PingSummary {
  sent: number;
  received: number;
}

export interface HostLookupResult {
  ip: string;
}

export interface Error {
  message: string;
  title: string;
}

export interface VersionRequest {
}

export interface VersionResponse {
  version: string;
}

export interface TracerouteRequest {
  host: string;
  protocol: Protocol;
}

export interface TracerouteResponse {
  reply?: TracerouteReply | undefined;
  timeout?: PingTimeout | undefined;
  error?: Error | undefined;
  completed?: Empty | undefined;
  lookup?: HostLookupResult | undefined;
}

export interface TracerouteReply {
  seq: number;
  ip: string;
  rtt: number;
}

export interface MtrRequest {
  host: string;
  protocol: Protocol;
}

export interface MtrResponse {
  pos: number;
  lookup?: HostLookupResult | undefined;
  host?: MtrHostLine | undefined;
  transmit?: MtrTransmitLine | undefined;
  ping?: MtrPingLine | undefined;
  dns?: MtrDnsLine | undefined;
  error?: Error | undefined;
}

export interface MtrHostLine {
  ip: string;
}

export interface MtrTransmitLine {
  seqnum: number;
}

export interface MtrPingLine {
  rtt: number;
  seqnum: number;
}

export interface MtrDnsLine {
  hostname: string;
}

export interface AgentRegisterRequest {
  name: string;
  provider: string;
}

export interface AgentRegisterResponse {
  success: boolean;
  message: string;
  country: string;
  location: string;
  latitude: number;
  longitude: number;
}

export interface TaskRequest {
  taskId: string;
  taskType: TaskType;
  ping?: PingRequest | undefined;
  mtr?: MtrRequest | undefined;
  traceroute?: TracerouteRequest | undefined;
  version?: VersionRequest | undefined;
}

export interface TaskResponse {
  taskId: string;
  taskType: TaskType;
  ping?: PingResponse | undefined;
  mtr?: MtrResponse | undefined;
  traceroute?: TracerouteResponse | undefined;
  version?: VersionResponse | undefined;
}

function createBasePingRequest(): PingRequest {
  return { host: "", protocol: 0 };
}

export const PingRequest: MessageFns<PingRequest> = {
  encode(message: PingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.host !== "") {
      writer.uint32(10).string(message.host);
    }
    if (message.protocol !== 0) {
      writer.uint32(16).int32(message.protocol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.protocol = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingRequest {
    return {
      host: isSet(object.host) ? globalThis.String(object.host) : "",
      protocol: isSet(object.protocol) ? protocolFromJSON(object.protocol) : 0,
    };
  },

  toJSON(message: PingRequest): unknown {
    const obj: any = {};
    if (message.host !== "") {
      obj.host = message.host;
    }
    if (message.protocol !== 0) {
      obj.protocol = protocolToJSON(message.protocol);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingRequest>, I>>(base?: I): PingRequest {
    return PingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingRequest>, I>>(object: I): PingRequest {
    const message = createBasePingRequest();
    message.host = object.host ?? "";
    message.protocol = object.protocol ?? 0;
    return message;
  },
};

function createBasePingResponse(): PingResponse {
  return { reply: undefined, timeout: undefined, summary: undefined, error: undefined, lookup: undefined };
}

export const PingResponse: MessageFns<PingResponse> = {
  encode(message: PingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reply !== undefined) {
      PingReply.encode(message.reply, writer.uint32(10).fork()).join();
    }
    if (message.timeout !== undefined) {
      PingTimeout.encode(message.timeout, writer.uint32(18).fork()).join();
    }
    if (message.summary !== undefined) {
      PingSummary.encode(message.summary, writer.uint32(26).fork()).join();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(34).fork()).join();
    }
    if (message.lookup !== undefined) {
      HostLookupResult.encode(message.lookup, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reply = PingReply.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.timeout = PingTimeout.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.summary = PingSummary.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lookup = HostLookupResult.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingResponse {
    return {
      reply: isSet(object.reply) ? PingReply.fromJSON(object.reply) : undefined,
      timeout: isSet(object.timeout) ? PingTimeout.fromJSON(object.timeout) : undefined,
      summary: isSet(object.summary) ? PingSummary.fromJSON(object.summary) : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      lookup: isSet(object.lookup) ? HostLookupResult.fromJSON(object.lookup) : undefined,
    };
  },

  toJSON(message: PingResponse): unknown {
    const obj: any = {};
    if (message.reply !== undefined) {
      obj.reply = PingReply.toJSON(message.reply);
    }
    if (message.timeout !== undefined) {
      obj.timeout = PingTimeout.toJSON(message.timeout);
    }
    if (message.summary !== undefined) {
      obj.summary = PingSummary.toJSON(message.summary);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.lookup !== undefined) {
      obj.lookup = HostLookupResult.toJSON(message.lookup);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingResponse>, I>>(base?: I): PingResponse {
    return PingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingResponse>, I>>(object: I): PingResponse {
    const message = createBasePingResponse();
    message.reply = (object.reply !== undefined && object.reply !== null)
      ? PingReply.fromPartial(object.reply)
      : undefined;
    message.timeout = (object.timeout !== undefined && object.timeout !== null)
      ? PingTimeout.fromPartial(object.timeout)
      : undefined;
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? PingSummary.fromPartial(object.summary)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.lookup = (object.lookup !== undefined && object.lookup !== null)
      ? HostLookupResult.fromPartial(object.lookup)
      : undefined;
    return message;
  },
};

function createBasePingReply(): PingReply {
  return { rtt: 0, ttl: 0, seq: 0, bytes: 0 };
}

export const PingReply: MessageFns<PingReply> = {
  encode(message: PingReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rtt !== 0) {
      writer.uint32(13).float(message.rtt);
    }
    if (message.ttl !== 0) {
      writer.uint32(16).int32(message.ttl);
    }
    if (message.seq !== 0) {
      writer.uint32(24).int32(message.seq);
    }
    if (message.bytes !== 0) {
      writer.uint32(32).int32(message.bytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.rtt = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ttl = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.seq = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.bytes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingReply {
    return {
      rtt: isSet(object.rtt) ? globalThis.Number(object.rtt) : 0,
      ttl: isSet(object.ttl) ? globalThis.Number(object.ttl) : 0,
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      bytes: isSet(object.bytes) ? globalThis.Number(object.bytes) : 0,
    };
  },

  toJSON(message: PingReply): unknown {
    const obj: any = {};
    if (message.rtt !== 0) {
      obj.rtt = message.rtt;
    }
    if (message.ttl !== 0) {
      obj.ttl = Math.round(message.ttl);
    }
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.bytes !== 0) {
      obj.bytes = Math.round(message.bytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingReply>, I>>(base?: I): PingReply {
    return PingReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingReply>, I>>(object: I): PingReply {
    const message = createBasePingReply();
    message.rtt = object.rtt ?? 0;
    message.ttl = object.ttl ?? 0;
    message.seq = object.seq ?? 0;
    message.bytes = object.bytes ?? 0;
    return message;
  },
};

function createBasePingTimeout(): PingTimeout {
  return { seq: 0 };
}

export const PingTimeout: MessageFns<PingTimeout> = {
  encode(message: PingTimeout, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== 0) {
      writer.uint32(8).int32(message.seq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingTimeout {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingTimeout();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingTimeout {
    return { seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0 };
  },

  toJSON(message: PingTimeout): unknown {
    const obj: any = {};
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingTimeout>, I>>(base?: I): PingTimeout {
    return PingTimeout.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingTimeout>, I>>(object: I): PingTimeout {
    const message = createBasePingTimeout();
    message.seq = object.seq ?? 0;
    return message;
  },
};

function createBasePingSummary(): PingSummary {
  return { sent: 0, received: 0 };
}

export const PingSummary: MessageFns<PingSummary> = {
  encode(message: PingSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sent !== 0) {
      writer.uint32(8).int32(message.sent);
    }
    if (message.received !== 0) {
      writer.uint32(16).int32(message.received);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sent = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.received = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingSummary {
    return {
      sent: isSet(object.sent) ? globalThis.Number(object.sent) : 0,
      received: isSet(object.received) ? globalThis.Number(object.received) : 0,
    };
  },

  toJSON(message: PingSummary): unknown {
    const obj: any = {};
    if (message.sent !== 0) {
      obj.sent = Math.round(message.sent);
    }
    if (message.received !== 0) {
      obj.received = Math.round(message.received);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingSummary>, I>>(base?: I): PingSummary {
    return PingSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingSummary>, I>>(object: I): PingSummary {
    const message = createBasePingSummary();
    message.sent = object.sent ?? 0;
    message.received = object.received ?? 0;
    return message;
  },
};

function createBaseHostLookupResult(): HostLookupResult {
  return { ip: "" };
}

export const HostLookupResult: MessageFns<HostLookupResult> = {
  encode(message: HostLookupResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ip !== "") {
      writer.uint32(10).string(message.ip);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostLookupResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostLookupResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostLookupResult {
    return { ip: isSet(object.ip) ? globalThis.String(object.ip) : "" };
  },

  toJSON(message: HostLookupResult): unknown {
    const obj: any = {};
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostLookupResult>, I>>(base?: I): HostLookupResult {
    return HostLookupResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostLookupResult>, I>>(object: I): HostLookupResult {
    const message = createBaseHostLookupResult();
    message.ip = object.ip ?? "";
    return message;
  },
};

function createBaseError(): Error {
  return { message: "", title: "" };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Error {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.message = object.message ?? "";
    message.title = object.title ?? "";
    return message;
  },
};

function createBaseVersionRequest(): VersionRequest {
  return {};
}

export const VersionRequest: MessageFns<VersionRequest> = {
  encode(_: VersionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VersionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVersionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): VersionRequest {
    return {};
  },

  toJSON(_: VersionRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<VersionRequest>, I>>(base?: I): VersionRequest {
    return VersionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VersionRequest>, I>>(_: I): VersionRequest {
    const message = createBaseVersionRequest();
    return message;
  },
};

function createBaseVersionResponse(): VersionResponse {
  return { version: "" };
}

export const VersionResponse: MessageFns<VersionResponse> = {
  encode(message: VersionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== "") {
      writer.uint32(10).string(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VersionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVersionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VersionResponse {
    return { version: isSet(object.version) ? globalThis.String(object.version) : "" };
  },

  toJSON(message: VersionResponse): unknown {
    const obj: any = {};
    if (message.version !== "") {
      obj.version = message.version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VersionResponse>, I>>(base?: I): VersionResponse {
    return VersionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VersionResponse>, I>>(object: I): VersionResponse {
    const message = createBaseVersionResponse();
    message.version = object.version ?? "";
    return message;
  },
};

function createBaseTracerouteRequest(): TracerouteRequest {
  return { host: "", protocol: 0 };
}

export const TracerouteRequest: MessageFns<TracerouteRequest> = {
  encode(message: TracerouteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.host !== "") {
      writer.uint32(10).string(message.host);
    }
    if (message.protocol !== 0) {
      writer.uint32(16).int32(message.protocol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TracerouteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTracerouteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.protocol = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TracerouteRequest {
    return {
      host: isSet(object.host) ? globalThis.String(object.host) : "",
      protocol: isSet(object.protocol) ? protocolFromJSON(object.protocol) : 0,
    };
  },

  toJSON(message: TracerouteRequest): unknown {
    const obj: any = {};
    if (message.host !== "") {
      obj.host = message.host;
    }
    if (message.protocol !== 0) {
      obj.protocol = protocolToJSON(message.protocol);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TracerouteRequest>, I>>(base?: I): TracerouteRequest {
    return TracerouteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TracerouteRequest>, I>>(object: I): TracerouteRequest {
    const message = createBaseTracerouteRequest();
    message.host = object.host ?? "";
    message.protocol = object.protocol ?? 0;
    return message;
  },
};

function createBaseTracerouteResponse(): TracerouteResponse {
  return { reply: undefined, timeout: undefined, error: undefined, completed: undefined, lookup: undefined };
}

export const TracerouteResponse: MessageFns<TracerouteResponse> = {
  encode(message: TracerouteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reply !== undefined) {
      TracerouteReply.encode(message.reply, writer.uint32(10).fork()).join();
    }
    if (message.timeout !== undefined) {
      PingTimeout.encode(message.timeout, writer.uint32(18).fork()).join();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(26).fork()).join();
    }
    if (message.completed !== undefined) {
      Empty.encode(message.completed, writer.uint32(34).fork()).join();
    }
    if (message.lookup !== undefined) {
      HostLookupResult.encode(message.lookup, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TracerouteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTracerouteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reply = TracerouteReply.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.timeout = PingTimeout.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.completed = Empty.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lookup = HostLookupResult.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TracerouteResponse {
    return {
      reply: isSet(object.reply) ? TracerouteReply.fromJSON(object.reply) : undefined,
      timeout: isSet(object.timeout) ? PingTimeout.fromJSON(object.timeout) : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      completed: isSet(object.completed) ? Empty.fromJSON(object.completed) : undefined,
      lookup: isSet(object.lookup) ? HostLookupResult.fromJSON(object.lookup) : undefined,
    };
  },

  toJSON(message: TracerouteResponse): unknown {
    const obj: any = {};
    if (message.reply !== undefined) {
      obj.reply = TracerouteReply.toJSON(message.reply);
    }
    if (message.timeout !== undefined) {
      obj.timeout = PingTimeout.toJSON(message.timeout);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.completed !== undefined) {
      obj.completed = Empty.toJSON(message.completed);
    }
    if (message.lookup !== undefined) {
      obj.lookup = HostLookupResult.toJSON(message.lookup);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TracerouteResponse>, I>>(base?: I): TracerouteResponse {
    return TracerouteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TracerouteResponse>, I>>(object: I): TracerouteResponse {
    const message = createBaseTracerouteResponse();
    message.reply = (object.reply !== undefined && object.reply !== null)
      ? TracerouteReply.fromPartial(object.reply)
      : undefined;
    message.timeout = (object.timeout !== undefined && object.timeout !== null)
      ? PingTimeout.fromPartial(object.timeout)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.completed = (object.completed !== undefined && object.completed !== null)
      ? Empty.fromPartial(object.completed)
      : undefined;
    message.lookup = (object.lookup !== undefined && object.lookup !== null)
      ? HostLookupResult.fromPartial(object.lookup)
      : undefined;
    return message;
  },
};

function createBaseTracerouteReply(): TracerouteReply {
  return { seq: 0, ip: "", rtt: 0 };
}

export const TracerouteReply: MessageFns<TracerouteReply> = {
  encode(message: TracerouteReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== 0) {
      writer.uint32(8).int32(message.seq);
    }
    if (message.ip !== "") {
      writer.uint32(18).string(message.ip);
    }
    if (message.rtt !== 0) {
      writer.uint32(29).float(message.rtt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TracerouteReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTracerouteReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.rtt = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TracerouteReply {
    return {
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      rtt: isSet(object.rtt) ? globalThis.Number(object.rtt) : 0,
    };
  },

  toJSON(message: TracerouteReply): unknown {
    const obj: any = {};
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.rtt !== 0) {
      obj.rtt = message.rtt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TracerouteReply>, I>>(base?: I): TracerouteReply {
    return TracerouteReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TracerouteReply>, I>>(object: I): TracerouteReply {
    const message = createBaseTracerouteReply();
    message.seq = object.seq ?? 0;
    message.ip = object.ip ?? "";
    message.rtt = object.rtt ?? 0;
    return message;
  },
};

function createBaseMtrRequest(): MtrRequest {
  return { host: "", protocol: 0 };
}

export const MtrRequest: MessageFns<MtrRequest> = {
  encode(message: MtrRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.host !== "") {
      writer.uint32(10).string(message.host);
    }
    if (message.protocol !== 0) {
      writer.uint32(16).int32(message.protocol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MtrRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMtrRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.protocol = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MtrRequest {
    return {
      host: isSet(object.host) ? globalThis.String(object.host) : "",
      protocol: isSet(object.protocol) ? protocolFromJSON(object.protocol) : 0,
    };
  },

  toJSON(message: MtrRequest): unknown {
    const obj: any = {};
    if (message.host !== "") {
      obj.host = message.host;
    }
    if (message.protocol !== 0) {
      obj.protocol = protocolToJSON(message.protocol);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MtrRequest>, I>>(base?: I): MtrRequest {
    return MtrRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MtrRequest>, I>>(object: I): MtrRequest {
    const message = createBaseMtrRequest();
    message.host = object.host ?? "";
    message.protocol = object.protocol ?? 0;
    return message;
  },
};

function createBaseMtrResponse(): MtrResponse {
  return {
    pos: 0,
    lookup: undefined,
    host: undefined,
    transmit: undefined,
    ping: undefined,
    dns: undefined,
    error: undefined,
  };
}

export const MtrResponse: MessageFns<MtrResponse> = {
  encode(message: MtrResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pos !== 0) {
      writer.uint32(8).uint32(message.pos);
    }
    if (message.lookup !== undefined) {
      HostLookupResult.encode(message.lookup, writer.uint32(18).fork()).join();
    }
    if (message.host !== undefined) {
      MtrHostLine.encode(message.host, writer.uint32(26).fork()).join();
    }
    if (message.transmit !== undefined) {
      MtrTransmitLine.encode(message.transmit, writer.uint32(34).fork()).join();
    }
    if (message.ping !== undefined) {
      MtrPingLine.encode(message.ping, writer.uint32(42).fork()).join();
    }
    if (message.dns !== undefined) {
      MtrDnsLine.encode(message.dns, writer.uint32(50).fork()).join();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MtrResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMtrResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pos = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lookup = HostLookupResult.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.host = MtrHostLine.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.transmit = MtrTransmitLine.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ping = MtrPingLine.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.dns = MtrDnsLine.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MtrResponse {
    return {
      pos: isSet(object.pos) ? globalThis.Number(object.pos) : 0,
      lookup: isSet(object.lookup) ? HostLookupResult.fromJSON(object.lookup) : undefined,
      host: isSet(object.host) ? MtrHostLine.fromJSON(object.host) : undefined,
      transmit: isSet(object.transmit) ? MtrTransmitLine.fromJSON(object.transmit) : undefined,
      ping: isSet(object.ping) ? MtrPingLine.fromJSON(object.ping) : undefined,
      dns: isSet(object.dns) ? MtrDnsLine.fromJSON(object.dns) : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: MtrResponse): unknown {
    const obj: any = {};
    if (message.pos !== 0) {
      obj.pos = Math.round(message.pos);
    }
    if (message.lookup !== undefined) {
      obj.lookup = HostLookupResult.toJSON(message.lookup);
    }
    if (message.host !== undefined) {
      obj.host = MtrHostLine.toJSON(message.host);
    }
    if (message.transmit !== undefined) {
      obj.transmit = MtrTransmitLine.toJSON(message.transmit);
    }
    if (message.ping !== undefined) {
      obj.ping = MtrPingLine.toJSON(message.ping);
    }
    if (message.dns !== undefined) {
      obj.dns = MtrDnsLine.toJSON(message.dns);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MtrResponse>, I>>(base?: I): MtrResponse {
    return MtrResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MtrResponse>, I>>(object: I): MtrResponse {
    const message = createBaseMtrResponse();
    message.pos = object.pos ?? 0;
    message.lookup = (object.lookup !== undefined && object.lookup !== null)
      ? HostLookupResult.fromPartial(object.lookup)
      : undefined;
    message.host = (object.host !== undefined && object.host !== null)
      ? MtrHostLine.fromPartial(object.host)
      : undefined;
    message.transmit = (object.transmit !== undefined && object.transmit !== null)
      ? MtrTransmitLine.fromPartial(object.transmit)
      : undefined;
    message.ping = (object.ping !== undefined && object.ping !== null)
      ? MtrPingLine.fromPartial(object.ping)
      : undefined;
    message.dns = (object.dns !== undefined && object.dns !== null) ? MtrDnsLine.fromPartial(object.dns) : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    return message;
  },
};

function createBaseMtrHostLine(): MtrHostLine {
  return { ip: "" };
}

export const MtrHostLine: MessageFns<MtrHostLine> = {
  encode(message: MtrHostLine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ip !== "") {
      writer.uint32(10).string(message.ip);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MtrHostLine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMtrHostLine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MtrHostLine {
    return { ip: isSet(object.ip) ? globalThis.String(object.ip) : "" };
  },

  toJSON(message: MtrHostLine): unknown {
    const obj: any = {};
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MtrHostLine>, I>>(base?: I): MtrHostLine {
    return MtrHostLine.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MtrHostLine>, I>>(object: I): MtrHostLine {
    const message = createBaseMtrHostLine();
    message.ip = object.ip ?? "";
    return message;
  },
};

function createBaseMtrTransmitLine(): MtrTransmitLine {
  return { seqnum: 0 };
}

export const MtrTransmitLine: MessageFns<MtrTransmitLine> = {
  encode(message: MtrTransmitLine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seqnum !== 0) {
      writer.uint32(8).uint32(message.seqnum);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MtrTransmitLine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMtrTransmitLine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seqnum = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MtrTransmitLine {
    return { seqnum: isSet(object.seqnum) ? globalThis.Number(object.seqnum) : 0 };
  },

  toJSON(message: MtrTransmitLine): unknown {
    const obj: any = {};
    if (message.seqnum !== 0) {
      obj.seqnum = Math.round(message.seqnum);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MtrTransmitLine>, I>>(base?: I): MtrTransmitLine {
    return MtrTransmitLine.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MtrTransmitLine>, I>>(object: I): MtrTransmitLine {
    const message = createBaseMtrTransmitLine();
    message.seqnum = object.seqnum ?? 0;
    return message;
  },
};

function createBaseMtrPingLine(): MtrPingLine {
  return { rtt: 0, seqnum: 0 };
}

export const MtrPingLine: MessageFns<MtrPingLine> = {
  encode(message: MtrPingLine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rtt !== 0) {
      writer.uint32(13).float(message.rtt);
    }
    if (message.seqnum !== 0) {
      writer.uint32(16).uint32(message.seqnum);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MtrPingLine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMtrPingLine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.rtt = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.seqnum = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MtrPingLine {
    return {
      rtt: isSet(object.rtt) ? globalThis.Number(object.rtt) : 0,
      seqnum: isSet(object.seqnum) ? globalThis.Number(object.seqnum) : 0,
    };
  },

  toJSON(message: MtrPingLine): unknown {
    const obj: any = {};
    if (message.rtt !== 0) {
      obj.rtt = message.rtt;
    }
    if (message.seqnum !== 0) {
      obj.seqnum = Math.round(message.seqnum);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MtrPingLine>, I>>(base?: I): MtrPingLine {
    return MtrPingLine.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MtrPingLine>, I>>(object: I): MtrPingLine {
    const message = createBaseMtrPingLine();
    message.rtt = object.rtt ?? 0;
    message.seqnum = object.seqnum ?? 0;
    return message;
  },
};

function createBaseMtrDnsLine(): MtrDnsLine {
  return { hostname: "" };
}

export const MtrDnsLine: MessageFns<MtrDnsLine> = {
  encode(message: MtrDnsLine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hostname !== "") {
      writer.uint32(10).string(message.hostname);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MtrDnsLine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMtrDnsLine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MtrDnsLine {
    return { hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "" };
  },

  toJSON(message: MtrDnsLine): unknown {
    const obj: any = {};
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MtrDnsLine>, I>>(base?: I): MtrDnsLine {
    return MtrDnsLine.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MtrDnsLine>, I>>(object: I): MtrDnsLine {
    const message = createBaseMtrDnsLine();
    message.hostname = object.hostname ?? "";
    return message;
  },
};

function createBaseAgentRegisterRequest(): AgentRegisterRequest {
  return { name: "", provider: "" };
}

export const AgentRegisterRequest: MessageFns<AgentRegisterRequest> = {
  encode(message: AgentRegisterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.provider !== "") {
      writer.uint32(18).string(message.provider);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AgentRegisterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAgentRegisterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AgentRegisterRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
    };
  },

  toJSON(message: AgentRegisterRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentRegisterRequest>, I>>(base?: I): AgentRegisterRequest {
    return AgentRegisterRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentRegisterRequest>, I>>(object: I): AgentRegisterRequest {
    const message = createBaseAgentRegisterRequest();
    message.name = object.name ?? "";
    message.provider = object.provider ?? "";
    return message;
  },
};

function createBaseAgentRegisterResponse(): AgentRegisterResponse {
  return { success: false, message: "", country: "", location: "", latitude: 0, longitude: 0 };
}

export const AgentRegisterResponse: MessageFns<AgentRegisterResponse> = {
  encode(message: AgentRegisterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.country !== "") {
      writer.uint32(26).string(message.country);
    }
    if (message.location !== "") {
      writer.uint32(34).string(message.location);
    }
    if (message.latitude !== 0) {
      writer.uint32(45).float(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(53).float(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AgentRegisterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAgentRegisterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.latitude = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.longitude = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AgentRegisterResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      latitude: isSet(object.latitude) ? globalThis.Number(object.latitude) : 0,
      longitude: isSet(object.longitude) ? globalThis.Number(object.longitude) : 0,
    };
  },

  toJSON(message: AgentRegisterResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.latitude !== 0) {
      obj.latitude = message.latitude;
    }
    if (message.longitude !== 0) {
      obj.longitude = message.longitude;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentRegisterResponse>, I>>(base?: I): AgentRegisterResponse {
    return AgentRegisterResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentRegisterResponse>, I>>(object: I): AgentRegisterResponse {
    const message = createBaseAgentRegisterResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    message.country = object.country ?? "";
    message.location = object.location ?? "";
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    return message;
  },
};

function createBaseTaskRequest(): TaskRequest {
  return { taskId: "", taskType: 0, ping: undefined, mtr: undefined, traceroute: undefined, version: undefined };
}

export const TaskRequest: MessageFns<TaskRequest> = {
  encode(message: TaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.taskType !== 0) {
      writer.uint32(16).int32(message.taskType);
    }
    if (message.ping !== undefined) {
      PingRequest.encode(message.ping, writer.uint32(26).fork()).join();
    }
    if (message.mtr !== undefined) {
      MtrRequest.encode(message.mtr, writer.uint32(34).fork()).join();
    }
    if (message.traceroute !== undefined) {
      TracerouteRequest.encode(message.traceroute, writer.uint32(42).fork()).join();
    }
    if (message.version !== undefined) {
      VersionRequest.encode(message.version, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.taskType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ping = PingRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.mtr = MtrRequest.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.traceroute = TracerouteRequest.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.version = VersionRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskRequest {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      taskType: isSet(object.taskType) ? taskTypeFromJSON(object.taskType) : 0,
      ping: isSet(object.ping) ? PingRequest.fromJSON(object.ping) : undefined,
      mtr: isSet(object.mtr) ? MtrRequest.fromJSON(object.mtr) : undefined,
      traceroute: isSet(object.traceroute) ? TracerouteRequest.fromJSON(object.traceroute) : undefined,
      version: isSet(object.version) ? VersionRequest.fromJSON(object.version) : undefined,
    };
  },

  toJSON(message: TaskRequest): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.taskType !== 0) {
      obj.taskType = taskTypeToJSON(message.taskType);
    }
    if (message.ping !== undefined) {
      obj.ping = PingRequest.toJSON(message.ping);
    }
    if (message.mtr !== undefined) {
      obj.mtr = MtrRequest.toJSON(message.mtr);
    }
    if (message.traceroute !== undefined) {
      obj.traceroute = TracerouteRequest.toJSON(message.traceroute);
    }
    if (message.version !== undefined) {
      obj.version = VersionRequest.toJSON(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskRequest>, I>>(base?: I): TaskRequest {
    return TaskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskRequest>, I>>(object: I): TaskRequest {
    const message = createBaseTaskRequest();
    message.taskId = object.taskId ?? "";
    message.taskType = object.taskType ?? 0;
    message.ping = (object.ping !== undefined && object.ping !== null)
      ? PingRequest.fromPartial(object.ping)
      : undefined;
    message.mtr = (object.mtr !== undefined && object.mtr !== null) ? MtrRequest.fromPartial(object.mtr) : undefined;
    message.traceroute = (object.traceroute !== undefined && object.traceroute !== null)
      ? TracerouteRequest.fromPartial(object.traceroute)
      : undefined;
    message.version = (object.version !== undefined && object.version !== null)
      ? VersionRequest.fromPartial(object.version)
      : undefined;
    return message;
  },
};

function createBaseTaskResponse(): TaskResponse {
  return { taskId: "", taskType: 0, ping: undefined, mtr: undefined, traceroute: undefined, version: undefined };
}

export const TaskResponse: MessageFns<TaskResponse> = {
  encode(message: TaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.taskType !== 0) {
      writer.uint32(16).int32(message.taskType);
    }
    if (message.ping !== undefined) {
      PingResponse.encode(message.ping, writer.uint32(26).fork()).join();
    }
    if (message.mtr !== undefined) {
      MtrResponse.encode(message.mtr, writer.uint32(34).fork()).join();
    }
    if (message.traceroute !== undefined) {
      TracerouteResponse.encode(message.traceroute, writer.uint32(42).fork()).join();
    }
    if (message.version !== undefined) {
      VersionResponse.encode(message.version, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.taskType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ping = PingResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.mtr = MtrResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.traceroute = TracerouteResponse.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.version = VersionResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskResponse {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      taskType: isSet(object.taskType) ? taskTypeFromJSON(object.taskType) : 0,
      ping: isSet(object.ping) ? PingResponse.fromJSON(object.ping) : undefined,
      mtr: isSet(object.mtr) ? MtrResponse.fromJSON(object.mtr) : undefined,
      traceroute: isSet(object.traceroute) ? TracerouteResponse.fromJSON(object.traceroute) : undefined,
      version: isSet(object.version) ? VersionResponse.fromJSON(object.version) : undefined,
    };
  },

  toJSON(message: TaskResponse): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.taskType !== 0) {
      obj.taskType = taskTypeToJSON(message.taskType);
    }
    if (message.ping !== undefined) {
      obj.ping = PingResponse.toJSON(message.ping);
    }
    if (message.mtr !== undefined) {
      obj.mtr = MtrResponse.toJSON(message.mtr);
    }
    if (message.traceroute !== undefined) {
      obj.traceroute = TracerouteResponse.toJSON(message.traceroute);
    }
    if (message.version !== undefined) {
      obj.version = VersionResponse.toJSON(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskResponse>, I>>(base?: I): TaskResponse {
    return TaskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskResponse>, I>>(object: I): TaskResponse {
    const message = createBaseTaskResponse();
    message.taskId = object.taskId ?? "";
    message.taskType = object.taskType ?? 0;
    message.ping = (object.ping !== undefined && object.ping !== null)
      ? PingResponse.fromPartial(object.ping)
      : undefined;
    message.mtr = (object.mtr !== undefined && object.mtr !== null) ? MtrResponse.fromPartial(object.mtr) : undefined;
    message.traceroute = (object.traceroute !== undefined && object.traceroute !== null)
      ? TracerouteResponse.fromPartial(object.traceroute)
      : undefined;
    message.version = (object.version !== undefined && object.version !== null)
      ? VersionResponse.fromPartial(object.version)
      : undefined;
    return message;
  },
};

export interface MtrSbWorker {
  Ping(request: PingRequest): Observable<PingResponse>;
  Version(request: VersionRequest): Promise<VersionResponse>;
  Traceroute(request: TracerouteRequest): Observable<TracerouteResponse>;
  Mtr(request: MtrRequest): Observable<MtrResponse>;
}

export const MtrSbWorkerServiceName = "MtrSbWorker";
export class MtrSbWorkerClientImpl implements MtrSbWorker {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MtrSbWorkerServiceName;
    this.rpc = rpc;
    this.Ping = this.Ping.bind(this);
    this.Version = this.Version.bind(this);
    this.Traceroute = this.Traceroute.bind(this);
    this.Mtr = this.Mtr.bind(this);
  }
  Ping(request: PingRequest): Observable<PingResponse> {
    const data = PingRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "Ping", data);
    return result.pipe(map((data) => PingResponse.decode(new BinaryReader(data))));
  }

  Version(request: VersionRequest): Promise<VersionResponse> {
    const data = VersionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Version", data);
    return promise.then((data) => VersionResponse.decode(new BinaryReader(data)));
  }

  Traceroute(request: TracerouteRequest): Observable<TracerouteResponse> {
    const data = TracerouteRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "Traceroute", data);
    return result.pipe(map((data) => TracerouteResponse.decode(new BinaryReader(data))));
  }

  Mtr(request: MtrRequest): Observable<MtrResponse> {
    const data = MtrRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "Mtr", data);
    return result.pipe(map((data) => MtrResponse.decode(new BinaryReader(data))));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
